version: "3"

services:
  bill-service:
    build:
      context: ../bill-service
      dockerfile: ./Dockerfile
    ports:
    - 8081:8081
  logistic-service:
    build:
      context: ../logistic-service
      dockerfile: ./Dockerfile
    ports:
    - 8082:8082
  checkout-service:
    build:
      context: ../checkout-service
      dockerfile: ./Dockerfile
    ports:
    - 8089:8089
    depends_on:
    - bill-service
    - logistic-service